version: '3.8'

services:
  gigachat-service:
    image: gigachat-normalizer:latest 
    ports:
      - "8090:8090"
    environment:
      - GIGACHAT_CREDENTIALS=NmYxZTE4ZWYtMGFlNy00NDI4LWFiZDItNjRkMjQ0ODFhYmExOmI5YzE5ZjdkLWVhNGMtNGFhMC1hMGI1LTgxMjFiZDhlYzZkZg==
    volumes:
      - ./server.log:/home/app/server.log 